{% set name = "abqpy" %}
{% set version = "2018.9" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c8e2a106a79ff0ba650fad01a0bb95d3ab3bbb331a47a5ee55b773408342a45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - abqpy = abqpy.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - auto-all
    - fire
    - pydantic
    - typeguard !=4.4.1
    - typing-extensions

test:
  imports:
    - abqpy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/haiiliin/abqpy
  summary: Type Hints for Abaqus/Python Scripting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://haiiliin.github.io/abqpy/
  dev_url: https://github.com/haiiliin/abqpy

extra:
  recipe-maintainers:
    - haiiliin
